// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
....................
....................
.......888..........
.......8888.........
.......88888........
........88888.......
.........88888888...
88......888888f888..
888...8888888888888.
.8888888888f81f88888
.8888888888f88888888
..888888888888888888
.888888888888888222.
888888888888888888..
88....88888...888...
.......88......8....
....................
....................
....................
....................
`;
            case "image3":
            case "marinheiro2":return img`
....................
....................
....................
........eeeeee......
.......eeeeeee......
.......eeeeeeeee....
.......eeeeeeeee....
.......eeeddddee....
........dddddddd....
........dddddddd....
........ddfddddd....
.......dddddddd.....
........dd2ddd......
........22ddd.......
........89d98.......
........98d89.......
........89d98.......
........98989.......
........fffff.......
..........ff........
`;
            case "image6":
            case "marinheiro1":return img`
....................
....................
....................
......eeeeee........
......eeeeeee.......
....eeeeeeeee.......
....eeeeeeeee.......
....eeddddeee.......
....dddddddd........
....dddddddd........
....dddddfdd........
.....dddddddd.......
......ddd2dd........
.......ddd22........
.......89d98........
.......98d89........
.......89d98........
.......98989........
.......fffff........
........ff..........
`;
            case "image2":
            case "marinheiro":return img`
....................
....................
....................
........eeee........
......eeeeeeee......
.....eeeeeeeeee.....
....eeeeeeeeeeee....
....eeeeeeeeeeee....
....eeeddddddeee....
...dddddddddddddd...
...ddddfddddfdddd...
...dddddddddddddd...
....ddd2dddd2ddd....
.....ddd2222ddd.....
....dd89898989dd....
....dd98989898dd....
....dd89898989dd....
.......ffffff.......
.......ff..ff.......
.......ff..ff.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
