// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
....................
....................
.......888..........
.......8888.........
.......88888........
........88888.......
.........88888888...
88......888888f888..
888...88888888888888
.8888888888f81f88888
.8888888888f88888888
..888888888888888888
.88888888888888222..
88888888888888888...
88....98888...888...
.......99......8....
....................
....................
....................
....................
`;
            case "image2":
            case "Ulisses":return img`
....................
....................
....................
....................
......ffff..........
....fff44fff........
...fff8998fff.......
..846894498648......
..ffffffffffff......
..ffffffddffff......
..ffddddddddff......
..ffdffddffdff......
...fd19dd91df.......
...fddddddddf.......
...fffddddfff.......
..449446644944......
..dd69844896dd......
..dd96988969dd......
.....ffffff.........
.....ff..ff.........
`;
            case "image3":
            case "Tiemap_nivel_1":return img`
.........e.............................................................e........
.........eee....................................eee.............................
.........ee...............................eee...................................
.........e...........................eee..............eee.......................
99999eeeeeeeeee..e..e..e..e..e..e...............................................
999999eeeeeeee...e..e..e..e..e..e...........................eee.................
9999999eeeeee....e..e..e..e..e..e...............................................
99999999eeee.....e..e..e..e..e..e...............................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
